CREATE OR REPLACE SEQUENCE id_useseq
MINVALUE 1
START WITH 1
INCREMENT BY 1
CACHE 50;

CREATE OR REPLACE SEQUENCE id_preseq
MINVALUE 1
START WITH 1
INCREMENT BY 1
CACHE 50;

CREATE OR REPLACE SEQUENCE seqid_incre
MINVALUE 1
START WITH 1
INCREMENT BY 1
CACHE 50;