CREATE SEQUENCE seqid_utilisateur
MINVALUE 1
START WITH 1
INCREMENT BY 1
CACHE 50;

CREATE SEQUENCE seqid_pressing
MINVALUE 1
START WITH 1
INCREMENT BY 1
CACHE 50;

CREATE SEQUENCE seqid_incre
MINVALUE 1
START WITH 1
INCREMENT BY 1
CACHE 50;